/*
 * This source file was generated by the Gradle 'init' task
 */
package com.jadon.todo;

import org.springframework.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ToDoApplication implements CommandLineRunner {
    public static void main(String[] args) {
        SpringApplication.run(ToDoApplication.class, args);
    }
}
